USE [WS]
GO

ALTER TABLE [AS].[RV_TBL_SIP_ACTUALIZA_SERIES] DROP CONSTRAINT [DF__RV_TBL_SI__Estad__18B6AB08]
GO

ALTER TABLE [AS].[RV_TBL_SIP_ACTUALIZA_SERIES] DROP CONSTRAINT [DF__RV_TBL_SI__Fecha__17C286CF]
GO

/****** Object:  Table [AS].[RV_TBL_SIP_ACTUALIZA_SERIES]    Script Date: 12/3/2025 16:35:51 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[AS].[RV_TBL_SIP_ACTUALIZA_SERIE]') AND type in (N'U'))
DROP TABLE [AS].[RV_TBL_SIP_ACTUALIZA_SERIES]
GO

CREATE SEQUENCE [AS].RV_TBL_SIP_GROUPID_SEQ
    START WITH 1
    INCREMENT BY 1;


CREATE TABLE [AS].[RV_TBL_SIP_ACTUALIZA_SERIES](
	[GoupID] INT  primary key default (NEXT VALUE FOR [AS].RV_TBL_SIP_GROUPID_SEQ),
	[Company] [nvarchar](20) NOT NULL,
	[Plant] [nvarchar](20) NOT NULL,
	[PartNum] [nvarchar](50) NOT NULL,
	[SerialNumber] [nvarchar](50) NOT NULL,
	[WareHouse] [nvarchar](50) NOT NULL,
	[BinNum] [nvarchar](50) NOT NULL,
	[Letra] [nvarchar](50) NULL,
	[SNReference] [nvarchar](250) NOT NULL,
	[SNStatus] [nvarchar](50) NOT NULL,
	[Fecha] [datetime] NOT NULL,
	[Estado] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [AS].[RV_TBL_SIP_ACTUALIZA_SERIES] ADD [GroupID] INT NOT NULL DEFAULT (NEXT VALUE FOR AS.RV_TBL_SIP_GROUPID_SEQ);


ALTER TABLE [AS].[RV_TBL_SIP_ACTUALIZA_SERIES] ADD  DEFAULT (getdate()) FOR [Fecha]
GO

ALTER TABLE [AS].[RV_TBL_SIP_ACTUALIZA_SERIES] ADD  DEFAULT ('Pendiente') FOR [Estado]
GO


-- Crear la secuencia para GroupID
CREATE SEQUENCE [AS].RV_TBL_SIP_GROUPID_SEQ
    START WITH 1
    INCREMENT BY 1;

-- Crear la tabla con GroupID asignado automáticamente desde la secuencia
CREATE TABLE [AS].[RV_TBL_SIP_ACTUALIZA_SERIE] (
    [GroupID]      INT NOT NULL DEFAULT (NEXT VALUE FOR [AS].RV_TBL_SIP_GROUPID_SEQ),
    [Company]      NVARCHAR(20) NOT NULL,
    [Plant]        NVARCHAR(20) NOT NULL,
    [PartNum]      NVARCHAR(50) NOT NULL,
    [SerialNumber] NVARCHAR(50) NOT NULL,
    [WareHouse]    NVARCHAR(50) NOT NULL,
    [BinNum]       NVARCHAR(50) NOT NULL,
    [Letra]        NVARCHAR(50) NULL,
    [SNReference]  NVARCHAR(250) NOT NULL,
    [SNStatus]     NVARCHAR(50) NOT NULL,
    [Fecha]        DATETIME NOT NULL DEFAULT GETDATE(),
    [Estado]       NVARCHAR(50) NOT NULL DEFAULT 'Pendiente',
    CONSTRAINT PK_RV_TBL_SIP_ACTUALIZA_SERIE PRIMARY KEY CLUSTERED ([GroupID] ASC, [Company] ASC, [PartNum] ASC,[SerialNumber] ASC)
) ON [PRIMARY];

ALTER SEQUENCE [AS].RV_TBL_SIP_GROUPID_SEQ RESTART WITH 1;
