declare @search varchar(50)
SET @search = '[CORPL11-EPIDB].[EpicorERPTest]'

SELECT 
ROUTINE_NAME
,ROUTINE_DEFINITION
FROM 
INFORMATION_SCHEMA.ROUTINES
WHERE 
ROUTINE_DEFINITION LIKE '%' + @search + '%'
AND ROUTINE_TYPE in ('PROCEDURE','VIEW')
ORDER BY
ROUTINE_NAME

