
EXEC SP_configure filestream_access_level,2
RECONFIGURE

CREATE DATABASE FilestreamDB
GO

Use FilestreamDB
GO

CREATE TABLE FILES
(
FILEID UNIQUEIDENTIFIER NOT NULL ROWGUIDCOL UNIQUE DEFAULT NEWID(),
PDF VARBINARY (MAX) FILESTREAM NULL
)
GO

--INSERCION 1
DECLARE @PDF as VARBINARY(MAX),
		@URLFILE NVARCHAR(MAX)= 'C:\Users\wrosario.RADIOVICTORIA\Downloads\FC -A-240-00000714.pdf';

SELECT	@PDF = CAST(BULKCOLUMN AS VARBINARY (MAX))
FROM OPENROWSET (BULK 'C:\Users\wrosario.RADIOVICTORIA\Downloads\FC -A-240-00000714.pdf', SINGLE_BLOB) AS DOC

INSERT INTO FILES(PDF)
VALUES(@PDF)


--INSERCION 2
DECLARE @PDF as VARBINARY(MAX),
		@URLFILE2 NVARCHAR(MAX)= 'C:\Users\wrosario.RADIOVICTORIA\Downloads\image (17).png';

SELECT	@PDF = CAST(BULKCOLUMN AS VARBINARY (MAX))
FROM OPENROWSET (BULK 'C:\Users\wrosario.RADIOVICTORIA\Downloads\image (17).png', SINGLE_BLOB) AS DOC

INSERT INTO FILES(PDF)
VALUES(@PDF)


--Script revision de contenido
Select PDF from FILES
Select PDF.pathname() from FILES
