  -- 1) Eliminar la FK actual
ALTER TABLE dbo.RV_TBL_SIP_ITEM_TP
DROP CONSTRAINT FK_RV_TBL_SIP_ITEM_ENCABEZADO_TRANSFERENCIA_P;
GO

-- 2) Crear la FK nuevamente con ON DELETE CASCADE
ALTER TABLE dbo.RV_TBL_SIP_ITEM_TP
WITH CHECK
ADD CONSTRAINT FK_RV_TBL_SIP_ITEM_ENCABEZADO_TRANSFERENCIA_P
FOREIGN KEY (TranNum)
REFERENCES dbo.RV_TBL_SIP_ENCABEZADO_TRANSFERENCIA_P (TranNum)
ON DELETE CASCADE;
GO

-- 3) (Opcional pero recomendado) asegurar que quede validada
ALTER TABLE dbo.RV_TBL_SIP_ITEM_TP
CHECK CONSTRAINT FK_RV_TBL_SIP_ITEM_ENCABEZADO_TRANSFERENCIA_P;
GO


-- Esto ahora debería borrar también los items
--DELETE FROM dbo.RV_TBL_SIP_ENCABEZADO_TRANSFERENCIA_P
WHERE TranNum = 175;
