RV_TBL_SIP_ENCABEZADO_COMPROBANTE
RV_TBL_SIP_DETALE_COMPROBANTE
RV_TBL_SIP_LOG_MENSAJE
RV_TBL_SIP_LOG_PC
--drop table RV_TBL_SIP_ENCABEZADO_COMPROBANTE
--drop table RV_TBL_SIP_DETALE_COMPROBANTE
CREATE TABLE [dbo].[RV_TBL_SIP_ENCABEZADO_COMPROBANTE](
	[Company] [nvarchar](50) NOT NULL,
	[Plant] [nvarchar](50) NOT NULL,
	[Tipo][varchar](2) NOT NULL,
	[TranNum] [int] IDENTITY(1,1) NOT NULL,
	[GroupID] [nvarchar](8) NOT NULL,
	[SoldToCustID] [int] NOT NULL,
	[InvoiceDate] [date] NOT NULL,
	[InvoiceRef] [nvarchar](50) NOT NULL,
	[InvRefLegNum][nvarchar](50) NOT NULL,
	[PONum][nvarchar](50) NOT NULL,
	[TermsCode][nvarchar](4) NOT NULL,
	[Comentario][nvarchar](1000) NOT NULL DEFAULT(''),
	[Fecha] [datetime] NOT NULL DEFAULT(GETDATE()),
	[Estado][nvarchar](50) NOT NULL DEFAULT('Pendiente'),
	[FechaModificacion] [datetime] NULL
PRIMARY KEY CLUSTERED 
(
	[TranNum] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[RV_TBL_SIP_DETALE_COMPROBANTE](
	[Company] [nvarchar](50) NOT NULL,
	[TranNum] [int] NOT NULL,
	[Linea] [int] NOT NULL,
	[PartNum] [nvarchar](50) NOT NULL,
	[Cantidad] [int] NOT NULL,
	[Precio][decimal](17,5) NOT NULL,
	[ShipToNum][nvarchar](14) NOT NULL,
	[Comentario][nvarchar](1000) NOT NULL DEFAULT(''),
	[Fecha] [datetime] NOT NULL DEFAULT(GETDATE()),
	[Estado][nvarchar](50) NOT NULL DEFAULT('Pendiente'),
	[FechaModificacion] [datetime] NULL
 CONSTRAINT [PK_RV_TBL_SIP_DETALE_COMPROBANTE] PRIMARY KEY CLUSTERED 
(
	[TranNum] ASC,
	[Linea] ASC,
	[PartNum] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RV_TBL_SIP_DETALE_COMPROBANTE]  WITH CHECK ADD  CONSTRAINT [FK_RV_TBL_SIP_DETALE_COMPROBANTE_ENCABEZADO_COMPROBANTE] FOREIGN KEY([TranNum])
REFERENCES [dbo].[RV_TBL_SIP_ENCABEZADO_COMPROBANTE] ([TranNum])
GO

ALTER TABLE [dbo].[RV_TBL_SIP_DETALE_COMPROBANTE] CHECK CONSTRAINT [FK_RV_TBL_SIP_DETALE_COMPROBANTE_ENCABEZADO_COMPROBANTE]
GO


CREATE TABLE [dbo].[RV_TBL_SIP_LOG_MENSAJE](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Codigo] [nvarchar](10) NULL,
	[Detalle] [varchar](250) NULL,
	[DetalleUsuario] [varchar](250) NULL,
	[TipoLog] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[RV_TBL_SIP_LOG_PC](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Codigo] [nvarchar](20) NOT NULL,
	[Fecha] [datetime] NULL,
	[descripcion] [nvarchar](max) NULL,
	[Estado] [nvarchar](10) NOT NULL,
	[Proceso] [nvarchar](50) NOT NULL,
	[JsonRequest] [nvarchar](max) NULL,
	[JsonResponse] [nvarchar](max) NULL,
 CONSTRAINT [PK_RV_TBL_SIP_LOG_PC] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO