
DECLARE			@Search varchar(50)
SET				@Search = '10.3.0.11'

SELECT			ROUTINE_NAME, ROUTINE_DEFINITION
FROM			INFORMATION_SCHEMA.ROUTINES
WHERE			ROUTINE_DEFINITION			LIKE	'%' + @Search + '%'
--	AND			ROUTINE_TYPE				=		'PROCEDURE'
ORDER BY		ROUTINE_NAME
